version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - elastic
    healthcheck:
        test: "curl http://elasticsearch:9200"
        interval: "1s"
        timeout: "3s"
        retries: 60

  web:
    build: ./web
    restart: always
    container_name: web
    ports:
      - 5000:5000
    environment:
      PYTHONUNBUFFERED: 0
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch

networks:
    elastic:
        driver: bridge