version: "3.7"
services:
  gitlab:
    image: "gitlab/gitlab-ce:latest"
    container_name: gitlab
    restart: always
    hostname: "gitlab.yunhacho.com"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url = 'gitlab.yunhacho.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - "/home/docker/gitlab/config:/etc/gitlab"
      - "/home/docker/gitlab/logs:/var/log/gitlab"
      - "/home/docker/gitlab/data:/var/opt/gitlab"
