def label = "webapp-${UUID.randomUUID().toString()}"
podTemplate(
	label: label, 
	containers: [
		//container image는 docker search 명령 이용
		containerTemplate(name: "docker-python", image: "python:3.7.2", ttyEnabled: true, command: "cat"),
		containerTemplate(name: "docker", image: "docker:stable", ttyEnabled: true, command: "cat"),
		containerTemplate(name: "helm", image: "dtzar/helm-kubectl", ttyEnabled: true, command: "cat")
	],
	//volume mount
	volumes: [
		hostPathVolume(hostPath: "//var/run/docker.sock", mountPath: "/var/run/docker.sock")
	]
)
{
	node(label) {

        stage('Clone repository') {
         checkout scm
        }
		
		try {
			stage("unit test"){
				container('docker-python'){
					sh "pip install -r requirements.txt"
					sh "pytest testCS.py"
				}
			}

			stage("Build Docker image"){
                container("docker"){
                    app=docker.build("jyh5530/web-analysis")
                }
            }

			stage("Push Docker image") {
				container("docker") {
					docker.withRegistry("https://registry.hub.docker.com", "dockerhubid") {
                        app.push("latest")
					}
				}
			}

			stage( "Deploy to Cluster" ) {
				container("helm") {
                    sh "helm repo add github-test https://yunhacho.github.io/helm-charts/"
                    sh "helm repo update"
                    sh "helm install webapp github-test/test --namespace deploy"
				}
			}
		}
		catch(e) {
			currentBuild.result = "FAILED"
		}
		
	}
}
